services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: grievance
      POSTGRES_USER: grievance
      POSTGRES_PASSWORD: grievance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # stays on default network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # stays on default network

  api:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    #networks:
    #  - default          # reach db/redis by their service names
    #  - grievance_net    # be reachable from Typebot as "grievance-api"
    
    # IMPORTANT: give a stable alias on grievance_net
    # Docker needs per-network aliases; use the extended form if you want explicit alias:
    networks:
       default: {}
       grievance_net:
         aliases:
           - grievance-api

networks:
  grievance_net:
    external: true  # created earlier via: docker network create grievance_net
  # "default" network is implicit; no need to declare it

volumes:
  pgdata:
