services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: grievance
      POSTGRES_USER: grievance
      POSTGRES_PASSWORD: grievance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # This service joins the default network and is reachable by other services.

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # This service also joins the default network.

  api:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    # This service connects to two networks:
    # 1. The "default" network to communicate with `db` and `redis`.
    # 2. The external "grievance_net" to be reachable from the Typebot container.
    networks:
      default: {}
      grievance_net:
        # On the grievance_net network, this service will be findable
        # using the stable hostname "grievance-api".
        aliases:
          - grievance-api

networks:
  grievance_net:
    external: true # This network must be created manually:
                   # docker network create grievance_net
  # The "default" network is created automatically by Docker Compose.

volumes:
  pgdata: